<?php
$helper = $this->helper('PayEye\PayEye\Helper\Data');
$apiVersion = $helper->getApiVersion();
$uiSide = $helper->getUiSide();
$uiSideDistance = $helper->getUiSideDistance();
$uiBottomDistance = $helper->getUiBottomDistance();
$uiZIndex = $helper->getUiZIndex();
$widgetMode = $helper->isOnClick() ? 'ON_CLICK' : 'FLOATING';
?>

<script>
    var payeye = {
        "platform": "MAGENTO",
        "apiUrl": "<?= $this->getBaseUrl() ?>rest/V<?= $apiVersion ?>/api-payeye",
        "side": "<?= mb_strtoupper($uiSide) ?>",
        "ui":{
            "zIndex": <?= $uiZIndex ?>,
            "position": {"bottom": "<?= $uiBottomDistance ?>px", "side": "<?= $uiSideDistance ?>px"},
            "mobile": {"open": false}
        },
        "widgetMode": "<?= $widgetMode ?>",
        "widgetModeBtnStyle": "STYLED_GREEN"
    }
</script>
